FROM node:18-slim AS build

WORKDIR /app
COPY frontend/package*.json .
RUN npm install
COPY frontend/ .
RUN npm run build

FROM node:18-slim
RUN npm install -g serve
WORKDIR /app
COPY --from=build /app/build build/
EXPOSE 3002
CMD ["serve", "-s", "build", "-l", "3002"]
